name: Changelog

on:
  workflow_run:
    workflows: [ "tests", "static" ]
    branches: [ main ]
    types:
      - completed
  push:
    branches: [ main ]

jobs:
  if: ${{ github.event.workflow_run.conclusion == 'success' }}
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './composer.json'
